version: '3.3'

services:
  server:
    image: maven:3.9-amazoncorretto-21-debian
    environment:
      DIETIDEALS24_GEO_API_KEY: ${DIETIDEALS24_GEO_API_KEY}
      DIETIDEALS24_GOOGLE_SMTP_PASSWORD: ${DIETIDEALS24_GOOGLE_SMTP_PASSWORD}
      DIETIDEALS24_GOOGLE_SMTP_USERNAME: "dietideals24@gmail.com"
      DIETIDEALS24_KEYSTORE_PATH: /ssl/dd24-keystore.p12
      DIETIDEALS24_KEYSTORE_PASSWORD: ${DIETIDEALS24_KEYSTORE_PASSWORD}
      DIETIDEALS24_KEYSTORE_ALIAS: dietideals24
      DIETIDEALS24_FRONTEND_URL: "https://localhost:4200"
      DIETIDEALS24_LOGO_URL: "https://localhost:4200/assets/logo.svg"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dietideals24passw"
      POSTGRES_HOST: "database"
      POSTGRES_PORT: 5433
      REDIS_HOST: "cache"
      REDIS_PORT: 6379
      DIETIDEALS24_AWS_S3_ACCESS_KEY: ${DIETIDEALS24_AWS_S3_ACCESS_KEY}
      DIETIDEALS24_AWS_S3_SECRET_KEY: ${DIETIDEALS24_AWS_S3_SECRET_KEY}
      DIETIDEALS24_AWS_CLOUDFRONT_DOMAIN: "https://d3i2cyifds6hhr.cloudfront.net"
      DIETIDEALS24_AWS_S3_REGION: "eu-south-1"
      DIETIDEALS24_AWS_S3_BUCKET_NAME: "dietideals24-uploads"
      DIETIDEALS24_GOOGLE_CLIENT_ID: ${DIETIDEALS24_GOOGLE_CLIENT_ID}
      DIETIDEALS24_GOOGLE_CLIENT_SECRET: ${DIETIDEALS24_GOOGLE_CLIENT_SECRET}
    command: sh -c "mvn package && java -jar target/DietiDeals24-backend-0.0.1-SNAPSHOT.jar"
    ports:
      - "80:80"
      - "8443:8443"
    volumes:
      - './server:/server'
      - './ssl:/ssl'
    working_dir: "/server"
    depends_on:
      database:
        condition: service_healthy
      cache:      
        condition: service_healthy

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dietideals24passw"
      POSTGRES_DB: "dietideals24"
    volumes:
      - ./postgres_volume:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:ro
    command: ["postgres", "-p", "5433"]
    healthcheck:
      test: pg_isready -U postgres -d dietideals24 -p 5433
      interval: 3s
      timeout: 900s
      retries: 200

  cache:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 900s
      retries: 300
